### ISSUE TITLE
zeus ➡ zenias

### ISSUE THREAD

**Issue by ghost** [DevBlend/zenias#71]
Fix README and other content which uses the name Zeus...

**Comment by mtancoigne** [comment]
I'm on it, but don't have permission to create new branches here

> unable to access 'https://github.com/DevBlend/DevBlend.git/': The requested URL returned error: 403

**Comment by ghost** [comment]
@mtancpigne, I've already fixed most of this, I'll push changes 🔜. Usually when someone assigns themselves to an issue, they are going to fix it 😜

**Comment by ghost** [comment]
OK lol just saw you submitted a PR,no worries I'll get rid of my changes. Remember if someone is assigned in future to leave it or wait...

**Comment by byteknacker** [comment]
@mtancoigne, you still have problems making new branches? Please PR from your fork. Yes let's leave the issue creator and assigned persons the responsibility to finish the issue. We need to trust each other to do great work.

**Comment by mtancoigne** [comment]
btw, as I can see, everyone started to do the job for its own language, so i'll only stick to PHP

**Comment by byteknacker** [comment]
@mtancoigne yes that is a great idea. Everyone splits his work into one thing and we all divide our labour. I focus on the software design and source code of main script.
